# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testruncase",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="testruncase",
            constraint=models.UniqueConstraint(
                fields=("test_run", "testcase"),
                name="executions_testruncase_test_run_testcase_uniq",
            ),
        ),
    ]
