# Generated by Django 4.2.30 on 2026-08-11 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_align_project_owner_and_member_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('user_requirement', models.TextField(verbose_name='用户需求')),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('ANALYZING', '需求分析中'), ('GENERATING_DATA', '生成测试数据'), ('GENERATING_CASE', '生成测试用例'), ('RUNNING', '执行测试中'), ('ANALYZING_RESULT', '结果分析中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], db_index=True, default='CREATED', max_length=32, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度')),
                ('plan', models.JSONField(blank=True, default=list, verbose_name='执行计划')),
                ('test_plan', models.JSONField(blank=True, default=dict, verbose_name='测试计划')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='运行上下文')),
                ('failure_analysis', models.JSONField(blank=True, default=dict, verbose_name='失败分析')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'AI Agent任务',
                'verbose_name_plural': 'AI Agent任务',
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=80, unique=True, verbose_name='资产编号')),
                ('asset_type', models.CharField(choices=[('data', '测试数据'), ('case', '测试用例'), ('api', 'API测试'), ('ui', 'UI自动化'), ('app', 'APP自动化'), ('performance', '性能测试'), ('report', '测试报告')], db_index=True, max_length=32, verbose_name='资产类型')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('source_model', models.CharField(blank=True, default='', max_length=100, verbose_name='来源模型')),
                ('source_id', models.CharField(blank=True, default='', max_length=80, verbose_name='来源ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_test_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_assets', to='projects.project', verbose_name='关联项目')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='agent.agenttask', verbose_name='Agent任务')),
            ],
            options={
                'verbose_name': 'Agent测试资产',
                'verbose_name_plural': 'Agent测试资产',
                'db_table': 'test_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('step_type', models.CharField(db_index=True, max_length=32, verbose_name='步骤类型')),
                ('action', models.CharField(max_length=300, verbose_name='动作')),
                ('tool_name', models.CharField(blank=True, default='', max_length=80, verbose_name='工具名称')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('SKIPPED', '跳过')], db_index=True, default='PENDING', max_length=20, verbose_name='状态')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'AI Agent步骤',
                'verbose_name_plural': 'AI Agent步骤',
                'db_table': 'agent_steps',
                'ordering': ['step', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('event', '事件'), ('plan', '计划'), ('tool_result', '工具结果'), ('analysis', '分析')], default='event', max_length=32, verbose_name='类型')),
                ('role', models.CharField(default='agent', max_length=32, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='结构化内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='agent.agentstep', verbose_name='步骤')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agent.agenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'AI Agent记忆',
                'verbose_name_plural': 'AI Agent记忆',
                'db_table': 'agent_memory',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=32, verbose_name='执行模块')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '执行中'), ('PASSED', '通过'), ('FAILED', '失败'), ('SKIPPED', '跳过')], db_index=True, default='PENDING', max_length=20, verbose_name='状态')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求/输入')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='响应/输出')),
                ('logs', models.TextField(blank=True, default='', verbose_name='日志')),
                ('screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='截图')),
                ('report_url', models.CharField(blank=True, default='', max_length=500, verbose_name='报告地址')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时毫秒')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_results', to='agent.testasset', verbose_name='资产')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_results', to='agent.agentstep', verbose_name='步骤')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='agent.agenttask', verbose_name='Agent任务')),
            ],
            options={
                'verbose_name': '测试执行结果',
                'verbose_name_plural': '测试执行结果',
                'db_table': 'test_execution_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'module'], name='test_execut_task_id_5a3f3a_idx'), models.Index(fields=['status'], name='test_execut_status_a86e67_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testasset',
            index=models.Index(fields=['asset_type'], name='test_assets_asset_t_f729d4_idx'),
        ),
        migrations.AddIndex(
            model_name='testasset',
            index=models.Index(fields=['task', 'asset_type'], name='test_assets_task_id_82d907_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['created_by', '-created_at'], name='agent_tasks_created_825699_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['status'], name='agent_tasks_status_77f28c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['task', 'status'], name='agent_steps_task_id_a96b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['step_type'], name='agent_steps_step_ty_a85fb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentstep',
            unique_together={('task', 'step')},
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['task', 'memory_type'], name='agent_memor_task_id_88f0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['created_at'], name='agent_memor_created_5b2a52_idx'),
        ),
    ]
