# Generated by Codex on 2026-08-11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('projects', '0005_align_project_owner_and_member_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='当前步骤'),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memories', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_type', models.CharField(choices=[('thought', 'Thought'), ('action', 'Action'), ('observation', 'Observation'), ('reflection', 'Reflection')], db_index=True, max_length=32, verbose_name='轨迹类型')),
                ('action', models.TextField(blank=True, default='', verbose_name='动作/思考')),
                ('tool', models.CharField(blank=True, default='', max_length=100, verbose_name='工具')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果')),
                ('status', models.CharField(blank=True, db_index=True, default='success', max_length=32, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='agent.agentstep', verbose_name='步骤')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='agent.agenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'Agent执行轨迹',
                'verbose_name_plural': 'Agent执行轨迹',
                'db_table': 'agent_execution_log',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['project', 'memory_type'], name='agent_memor_project_04c30a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['task', 'trace_type'], name='agent_execu_task_id_f94081_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['task', 'created_at'], name='agent_execu_task_id_468812_idx'),
        ),
    ]
