# Generated by Codex on 2026-08-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_react_agent_core'),
        ('projects', '0005_align_project_owner_and_member_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmemory',
            name='memory_type',
            field=models.CharField(choices=[('event', '事件'), ('plan', '计划'), ('tool_result', '工具结果'), ('analysis', '分析'), ('system_knowledge', '系统知识'), ('business_flow', '业务流程'), ('api_knowledge', '接口知识'), ('database_knowledge', '数据库知识'), ('security_knowledge', '安全知识')], default='event', max_length=32, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agent.agenttask', verbose_name='任务'),
        ),
        migrations.CreateModel(
            name='AgentKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('document_type', models.CharField(choices=[('prd', 'PRD'), ('api', '接口文档'), ('database', '数据库设计'), ('requirement', '需求说明'), ('bug', '历史Bug'), ('other', '其他')], db_index=True, default='other', max_length=32, verbose_name='文档类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='文档内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('embedding_model', models.CharField(blank=True, default='local-hash-embedding', max_length=100, verbose_name='Embedding模型')),
                ('status', models.CharField(db_index=True, default='indexed', max_length=32, verbose_name='状态')),
                ('chunks_count', models.PositiveIntegerField(default=0, verbose_name='分片数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_documents', to='projects.project', verbose_name='关联项目')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'Agent知识文档',
                'verbose_name_plural': 'Agent知识文档',
                'db_table': 'agent_knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分片序号')),
                ('content', models.TextField(verbose_name='内容')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='Embedding向量')),
                ('tokens', models.PositiveIntegerField(default=0, verbose_name='估算Token数')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agent.agentknowledgedocument', verbose_name='文档')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_chunks', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'Agent知识分片',
                'verbose_name_plural': 'Agent知识分片',
                'db_table': 'agent_knowledge_chunks',
                'ordering': ['document_id', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='agentknowledgedocument',
            index=models.Index(fields=['project', 'document_type'], name='agent_knowl_project_843953_idx'),
        ),
        migrations.AddIndex(
            model_name='agentknowledgedocument',
            index=models.Index(fields=['status'], name='agent_knowl_status_bdbda8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentknowledgechunk',
            index=models.Index(fields=['project', 'created_at'], name='agent_knowl_project_815062_idx'),
        ),
    ]
