# Generated by Django 4.2.30 on 2026-08-13 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_align_project_owner_and_member_constraints'),
        ('agent', '0008_clarify_historical_exploration'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2ETask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(verbose_name='自然语言需求')),
                ('scenario', models.JSONField(blank=True, default=dict, verbose_name='测试场景')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('test_data', models.JSONField(blank=True, default=dict, verbose_name='测试数据')),
                ('expected_result', models.TextField(blank=True, default='', verbose_name='预期结果')),
                ('executor_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], db_index=True, default='web', max_length=16, verbose_name='执行器类型')),
                ('target_url', models.URLField(blank=True, default='', max_length=2048, verbose_name='Web 目标地址')),
                ('mobile_config', models.JSONField(blank=True, default=dict, verbose_name='移动端配置')),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('PLANNING', '规划中'), ('NEEDS_INPUT', '待补充执行条件'), ('READY', '待执行'), ('QUEUED', '排队中'), ('RUNNING', '执行中'), ('ANALYZING', '分析中'), ('REPORTING', '生成报告中'), ('PASSED', '通过'), ('FAILED', '失败'), ('CANCELLED', '已取消')], db_index=True, default='CREATED', max_length=24, verbose_name='状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='AI 分析')),
                ('report_url', models.CharField(blank=True, default='', max_length=500, verbose_name='报告地址')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('trace_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='链路 ID')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Celery 任务 ID')),
                ('execution_attempt', models.PositiveIntegerField(default=0, verbose_name='执行次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e2e_task', to='agent.agenttask', verbose_name='通用 Agent 任务')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e2e_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e2e_tasks', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'E2E 测试任务',
                'verbose_name_plural': 'E2E 测试任务',
                'db_table': 'e2e_task',
                'ordering': ['-created_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='E2EExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='执行次数')),
                ('step', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('step_name', models.CharField(blank=True, default='', max_length=300, verbose_name='步骤名称')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '执行中'), ('PASSED', '通过'), ('FAILED', '失败'), ('SKIPPED', '跳过')], db_index=True, default='PENDING', max_length=16, verbose_name='状态')),
                ('screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='截图')),
                ('video', models.CharField(blank=True, default='', max_length=500, verbose_name='视频')),
                ('console_log', models.JSONField(blank=True, default=list, verbose_name='Console 日志')),
                ('network_log', models.JSONField(blank=True, default=list, verbose_name='网络日志')),
                ('device_log', models.TextField(blank=True, default='', verbose_name='设备日志')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时毫秒')),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='agent.e2etask', verbose_name='E2E 任务')),
            ],
            options={
                'verbose_name': 'E2E 执行日志',
                'verbose_name_plural': 'E2E 执行日志',
                'db_table': 'e2e_execution_log',
                'ordering': ['attempt', 'step', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='e2etask',
            index=models.Index(fields=['project', '-created_time'], name='e2e_task_project_c690c3_idx'),
        ),
        migrations.AddIndex(
            model_name='e2etask',
            index=models.Index(fields=['created_by', '-created_time'], name='e2e_task_created_90af7c_idx'),
        ),
        migrations.AddIndex(
            model_name='e2etask',
            index=models.Index(fields=['status', '-created_time'], name='e2e_task_status_95f3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='e2eexecutionlog',
            index=models.Index(fields=['task', 'attempt', 'status'], name='e2e_executi_task_id_fb4b03_idx'),
        ),
        migrations.AddIndex(
            model_name='e2eexecutionlog',
            index=models.Index(fields=['status', '-created_time'], name='e2e_executi_status_6e4b2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='e2eexecutionlog',
            constraint=models.UniqueConstraint(fields=('task', 'attempt', 'step'), name='uniq_e2e_task_attempt_step'),
        ),
    ]
