# Generated by Codex on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_e2e_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('CREATED', '已创建'),
                    ('ANALYZING', '需求分析中'),
                    ('GENERATING_DATA', '生成测试数据'),
                    ('GENERATING_CASE', '生成测试用例'),
                    ('RUNNING', '执行测试中'),
                    ('ANALYZING_RESULT', '结果分析中'),
                    ('NEEDS_INPUT', '待补充执行条件'),
                    ('COMPLETED', '已完成'),
                    ('FAILED', '失败'),
                    ('STOPPED', '已停止'),
                ],
                db_index=True,
                default='CREATED',
                max_length=32,
                verbose_name='状态',
            ),
        ),
    ]
