# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_owner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"),
                name="projects_projectmember_project_user_uniq",
            ),
        ),
    ]
