# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_automation", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apptestsuitecase",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="apptestsuitecase",
            constraint=models.UniqueConstraint(
                fields=("test_suite", "test_case"),
                name="app_automation_apptestsuitecase_test_suite_test_case_uniq",
            ),
        ),
    ]
