# Generated by Django 4.2 on 2026-07-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0021_add_checkbox_toggle_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='测试目标')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('planning', '规划中'), ('ready', '待执行'), ('executing', '执行中'), ('analyzing', '分析中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='任务进度')),
                ('auto_execute', models.BooleanField(default=False, verbose_name='规划完成后自动执行')),
                ('plan', models.JSONField(blank=True, default=dict, verbose_name='测试计划')),
                ('execution_ids', models.JSONField(blank=True, default=list, verbose_name='执行记录 ID')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果汇总')),
                ('failure_analysis', models.JSONField(blank=True, default=dict, verbose_name='失败分析')),
                ('defect_draft', models.JSONField(blank=True, default=list, verbose_name='缺陷草稿')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery 任务 ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='app_automation.apppackage', verbose_name='应用包名')),
                ('current_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_agent_tasks', to='app_automation.apptestexecution', verbose_name='当前执行记录')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_tasks', to='app_automation.appdevice', verbose_name='执行设备')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='app_automation.appproject', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_agent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': 'APP AI Agent 任务',
                'verbose_name_plural': 'APP AI Agent 任务',
                'db_table': 'app_agent_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_agent_user_created_idx'), models.Index(fields=['project', 'status'], name='app_agent_project_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppAgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(db_index=True, max_length=40, verbose_name='阶段')),
                ('level', models.CharField(choices=[('info', '信息'), ('success', '成功'), ('warning', '警告'), ('error', '错误')], default='info', max_length=20, verbose_name='级别')),
                ('message', models.CharField(max_length=500, verbose_name='事件信息')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app_automation.appagenttask', verbose_name='Agent 任务')),
            ],
            options={
                'verbose_name': 'APP AI Agent 事件',
                'verbose_name_plural': 'APP AI Agent 事件',
                'db_table': 'app_agent_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='app_agent_event_time_idx')],
            },
        ),
    ]
