# Generated by Django 4.2 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0022_app_agent_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appagenttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '等待中'),
                    ('planning', '规划中'),
                    ('review_required', '待评审草稿'),
                    ('ready', '待执行'),
                    ('executing', '执行中'),
                    ('analyzing', '分析中'),
                    ('completed', '已完成'),
                    ('failed', '失败'),
                    ('stopped', '已停止'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
                verbose_name='任务状态',
            ),
        ),
    ]
