# Generated by Django 5.2 for RunnerGo APP Agent phase four.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0024_app_agent_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appagenttask',
            name='execution_mode',
            field=models.CharField(choices=[('standard', '标准任务'), ('matrix_child', '兼容性矩阵子任务')], db_index=True, default='standard', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AddField(
            model_name='appagenttask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='app_automation.appagenttask', verbose_name='父 Agent 任务'),
        ),
        migrations.AlterField(
            model_name='appagenttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '等待中'), ('planning', '规划中'), ('review_required', '待评审草稿'),
                    ('ready', '待执行'), ('executing', '执行中'), ('runtime_executing', '自治执行中'),
                    ('awaiting_approval', '等待敏感操作审批'), ('matrix_executing', '兼容性矩阵执行中'),
                    ('matrix_approval', '兼容性矩阵等待审批'), ('analyzing', '分析中'),
                    ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
                verbose_name='任务状态',
            ),
        ),
        migrations.AddField(
            model_name='appagentruntimesession',
            name='telemetry_enabled',
            field=models.BooleanField(default=True, verbose_name='采集性能与崩溃遥测'),
        ),
        migrations.AddField(
            model_name='appagentruntimesession',
            name='telemetry_interval_steps',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='遥测采样步骤间隔'),
        ),
        migrations.AddField(
            model_name='appagentruntimesession',
            name='telemetry_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='遥测汇总'),
        ),
        migrations.CreateModel(
            name='AppAgentMatrixRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='矩阵名称')),
                ('status', models.CharField(choices=[('pending', '等待调度'), ('running', '执行中'), ('awaiting_approval', '等待审批'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], db_index=True, default='pending', max_length=24, verbose_name='矩阵状态')),
                ('max_concurrency', models.PositiveSmallIntegerField(default=2, verbose_name='最大并发设备数')),
                ('budgets', models.JSONField(blank=True, default=dict, verbose_name='单设备运行预算')),
                ('device_ids', models.JSONField(blank=True, default=list, verbose_name='设备 ID 列表')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='兼容性汇总')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_runs', to='app_automation.appagenttask', verbose_name='基础 Agent 任务')),
            ],
            options={
                'verbose_name': 'APP Agent 兼容性矩阵',
                'verbose_name_plural': 'APP Agent 兼容性矩阵',
                'db_table': 'app_agent_matrix_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['base_task', '-created_at'], name='app_matrix_task_time_idx'), models.Index(fields=['status', '-updated_at'], name='app_matrix_status_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppAgentMatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待调度'), ('queued', '已入队'), ('running', '执行中'), ('awaiting_approval', '等待审批'), ('completed', '通过'), ('failed', '失败'), ('budget_exhausted', '预算耗尽'), ('stopped', '已停止')], db_index=True, default='pending', max_length=24, verbose_name='单元状态')),
                ('platform', models.CharField(blank=True, default='', max_length=20, verbose_name='平台快照')),
                ('platform_version', models.CharField(blank=True, default='', max_length=50, verbose_name='系统版本快照')),
                ('compatibility', models.CharField(blank=True, default='pending', max_length=30, verbose_name='兼容性结论')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='执行汇总')),
                ('telemetry_summary', models.JSONField(blank=True, default=dict, verbose_name='遥测汇总')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_matrix_cells', to='app_automation.appdevice', verbose_name='执行设备')),
                ('matrix_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='app_automation.appagentmatrixrun', verbose_name='兼容性矩阵')),
                ('runtime_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_cell', to='app_automation.appagentruntimesession', verbose_name='自治会话')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_cell', to='app_automation.appagenttask', verbose_name='设备子任务')),
            ],
            options={
                'verbose_name': 'APP Agent 兼容性矩阵单元',
                'verbose_name_plural': 'APP Agent 兼容性矩阵单元',
                'db_table': 'app_agent_matrix_cells',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['matrix_run', 'status'], name='app_matrix_cell_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('matrix_run', 'device'), name='app_matrix_device_uniq')],
            },
        ),
    ]
