# Generated by Django 4.2.7 on 2026-05-29 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0003_alter_testcase_author"),
        ("testsuites", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsuitecase",
            name="testcase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_suites",
                to="testcases.testcase",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitecase",
            name="testsuite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suite_cases",
                to="testsuites.testsuite",
            ),
        ),
    ]
