# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsuites", "0003_alter_testsuitecase_testcase_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testsuitecase",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="testsuitecase",
            constraint=models.UniqueConstraint(
                fields=("testsuite", "testcase"),
                name="testsuites_testsuitecase_testsuite_testcase_uniq",
            ),
        ),
    ]
