# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewassignment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reviewassignment",
            constraint=models.UniqueConstraint(
                fields=("review", "reviewer"),
                name="reviews_reviewassignment_review_reviewer_uniq",
            ),
        ),
    ]
