# Generated by Django 4.2.30 on 2026-07-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0005_align_testcase_author_and_step_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0016_testcasegenerationtask_monotonic_review'),
        ('projects', '0005_align_project_owner_and_member_constraints'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='接口路径')),
                ('service', models.CharField(blank=True, default='', max_length=120, verbose_name='所属服务')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('status', models.CharField(choices=[('designing', '设计中'), ('active', '可用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_api_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_assets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口资产',
                'verbose_name_plural': '接口资产',
                'db_table': 'test_asset_apis',
                'ordering': ['method', 'path'],
            },
        ),
        migrations.CreateModel(
            name='AutomationScriptAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('script_type', models.CharField(choices=[('robot', 'Robot Framework'), ('pytest', 'Pytest'), ('playwright', 'Playwright'), ('appium', 'Appium'), ('postman', 'Postman'), ('other', '其他')], default='pytest', max_length=20, verbose_name='脚本类型')),
                ('path', models.CharField(max_length=500, verbose_name='脚本路径')),
                ('repository', models.CharField(blank=True, default='', max_length=300, verbose_name='仓库地址')),
                ('entrypoint', models.CharField(blank=True, default='', max_length=300, verbose_name='执行入口')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_automation_script_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_script_assets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '自动化脚本资产',
                'verbose_name_plural': '自动化脚本资产',
                'db_table': 'test_asset_automation_scripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_key', models.CharField(max_length=80, verbose_name='缺陷编号')),
                ('title', models.CharField(max_length=300, verbose_name='缺陷标题')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('fixing', '修复中'), ('fixed', '已修复'), ('verified', '已验证'), ('closed', '已关闭'), ('reopened', '重新打开')], default='open', max_length=20, verbose_name='状态')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='外部链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_defect_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_assets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '缺陷资产',
                'verbose_name_plural': '缺陷资产',
                'db_table': 'test_asset_defects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='页面/元素名称')),
                ('platform', models.CharField(choices=[('web', 'Web'), ('h5', 'H5'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20, verbose_name='平台')),
                ('route', models.CharField(blank=True, default='', max_length=500, verbose_name='页面路径')),
                ('element_name', models.CharField(blank=True, default='', max_length=200, verbose_name='元素名称')),
                ('selector', models.CharField(blank=True, default='', max_length=500, verbose_name='定位信息')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('status', models.CharField(choices=[('designing', '设计中'), ('active', '可用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_page_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_assets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '页面资产',
                'verbose_name_plural': '页面资产',
                'db_table': 'test_asset_pages',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestAssetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_key', models.CharField(max_length=80, verbose_name='需求编号')),
                ('title', models.CharField(max_length=300, verbose_name='需求标题')),
                ('module', models.CharField(blank=True, default='', max_length=120, verbose_name='所属模块')),
                ('description', models.TextField(blank=True, default='', verbose_name='需求描述')),
                ('acceptance_criteria', models.TextField(blank=True, default='', verbose_name='验收标准')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewing', '评审中'), ('approved', '已确认'), ('changed', '已变更'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('ai', 'AI分析'), ('imported', '外部导入')], default='manual', max_length=20, verbose_name='来源')),
                ('external_url', models.URLField(blank=True, default='', verbose_name='外部链接')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requirements', to='requirement_analysis.businessrequirement', verbose_name='关联AI需求')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_asset_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_asset_requirements', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requirements', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试资产需求',
                'verbose_name_plural': '测试资产需求',
                'db_table': 'test_asset_requirements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('api', '接口'), ('page', '页面'), ('testcase', '测试用例'), ('automation_script', '自动化脚本'), ('defect', '缺陷'), ('report', '测试报告'), ('generated_case', 'AI生成用例'), ('business_requirement', 'AI业务需求')], max_length=30, verbose_name='资产类型')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='关系说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='test_assets.apiasset', verbose_name='接口')),
                ('automation_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='test_assets.automationscriptasset', verbose_name='自动化脚本')),
                ('business_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_links', to='requirement_analysis.businessrequirement', verbose_name='AI业务需求')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_asset_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='test_assets.defectasset', verbose_name='缺陷')),
                ('generated_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='requirement_analysis.generatedtestcase', verbose_name='AI生成用例')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='test_assets.pageasset', verbose_name='页面')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_asset_links', to='projects.project', verbose_name='所属项目')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='reports.testreport', verbose_name='测试报告')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='test_assets.testassetrequirement', verbose_name='关联需求')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试资产关系',
                'verbose_name_plural': '测试资产关系',
                'db_table': 'test_asset_links',
                'ordering': ['asset_type', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testassetrequirement',
            index=models.Index(fields=['project', 'requirement_key'], name='test_asset__project_604311_idx'),
        ),
        migrations.AddIndex(
            model_name='testassetrequirement',
            index=models.Index(fields=['project', 'status'], name='test_asset__project_cb5bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='testassetrequirement',
            index=models.Index(fields=['project', 'priority'], name='test_asset__project_c7de8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testassetrequirement',
            unique_together={('project', 'requirement_key')},
        ),
        migrations.AddIndex(
            model_name='testassetlink',
            index=models.Index(fields=['project', 'requirement', 'asset_type'], name='test_asset__project_fb0729_idx'),
        ),
        migrations.AddIndex(
            model_name='pageasset',
            index=models.Index(fields=['project', 'platform'], name='test_asset__project_da70fa_idx'),
        ),
        migrations.AddIndex(
            model_name='defectasset',
            index=models.Index(fields=['project', 'status'], name='test_asset__project_bcbf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='defectasset',
            index=models.Index(fields=['project', 'severity'], name='test_asset__project_f06b84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='defectasset',
            unique_together={('project', 'defect_key')},
        ),
        migrations.AddIndex(
            model_name='automationscriptasset',
            index=models.Index(fields=['project', 'script_type'], name='test_asset__project_3bc5c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationscriptasset',
            unique_together={('project', 'path')},
        ),
        migrations.AddIndex(
            model_name='apiasset',
            index=models.Index(fields=['project', 'method', 'path'], name='test_asset__project_24486c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiasset',
            unique_together={('project', 'method', 'path')},
        ),
    ]
