# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement_analysis", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="businessrequirement",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="generatedtestcase",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="businessrequirement",
            constraint=models.UniqueConstraint(
                fields=("analysis", "requirement_id"),
                name="requirement_analysis_businessrequirement_analysis_requiremen",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedtestcase",
            constraint=models.UniqueConstraint(
                fields=("requirement", "case_id"),
                name="requirement_analysis_generatedtestcase_requirement_case_id_u",
            ),
        ),
    ]
