# Generated by Codex on 2026-07-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('requirement_analysis', '0017_business_rule_graph_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypeUnderstandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资产标题')),
                ('file', models.FileField(upload_to='prototype_understanding/%Y/%m/', verbose_name='原型/文档文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('asset_type', models.CharField(choices=[('image', '图片/原型图'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('swagger', 'Swagger'), ('postman', 'Postman'), ('text', '文本'), ('other', '其他')], db_index=True, default='other', max_length=20, verbose_name='资产类型')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('analyzed', '已识别'), ('draft_generated', '已生成步骤草稿'), ('failed', '识别失败')], db_index=True, default='uploaded', max_length=24, verbose_name='处理状态')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='文件哈希')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='提取文本')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='页面/元素/接口识别结果')),
                ('ui_flow_draft', models.JSONField(blank=True, default=dict, verbose_name='UI 自动化步骤草稿')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prototype_understanding_assets', to='projects.project', verbose_name='关联项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototype_understanding_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '原型理解资产',
                'verbose_name_plural': '原型理解资产',
                'db_table': 'prototype_understanding_assets',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['uploaded_by', '-created_at'], name='proto_asset_user_time_idx'),
                    models.Index(fields=['project', 'status'], name='proto_asset_project_status_idx'),
                ],
            },
        ),
    ]
