# Generated by Django 4.2.7 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0022_business_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdocument',
            name='content_hash',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name='文件内容哈希',
            ),
        ),
    ]
