# Generated by Django 4.2.30 on 2026-08-13 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_align_project_owner_and_member_constraints'),
        ('requirement_analysis', '0025_alter_generationconfig_review_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='skill_context',
            field=models.JSONField(blank=True, default=list, verbose_name='本次生成采用的Skill快照'),
        ),
        migrations.CreateModel(
            name='TestSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Skill名称')),
                ('identifier', models.SlugField(max_length=120, verbose_name='Skill标识')),
                ('version', models.CharField(default='1.0.0', max_length=40, verbose_name='版本')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('storage_path', models.CharField(max_length=255, unique=True, verbose_name='存储目录')),
                ('entrypoint', models.CharField(default='SKILL.md', max_length=255, verbose_name='入口文件')),
                ('manifest', models.JSONField(blank=True, default=list, verbose_name='文件清单')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='文件数')),
                ('total_size', models.PositiveIntegerField(default=0, verbose_name='总大小(bytes)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_skills', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_skills', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '测试Skill',
                'verbose_name_plural': '测试Skills',
                'db_table': 'test_skill',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='selected_skills',
            field=models.ManyToManyField(blank=True, related_name='generation_tasks', to='requirement_analysis.testskill', verbose_name='本次生成选择的Skills'),
        ),
        migrations.AddConstraint(
            model_name='testskill',
            constraint=models.UniqueConstraint(fields=('project', 'identifier'), name='uniq_test_skill_project_identifier'),
        ),
        migrations.AddConstraint(
            model_name='testskill',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('identifier',), name='uniq_global_test_skill_identifier'),
        ),
    ]
