# Generated by Django 4.2.7 on 2026-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0003_alter_testcase_author"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testcasestep",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="testcasestep",
            constraint=models.UniqueConstraint(
                fields=("testcase", "step_number"),
                name="testcases_testcasestep_testcase_step_number_uniq",
            ),
        ),
    ]
