{{/* ===== ZooKeeper ===== */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: zookeeper
    {{- include "runnergo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: {{ .Values.messaging.zookeeper.image }}
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
---
{{/* ===== Kafka ===== */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
    {{- include "runnergo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.messaging.kafka.image }}
        envFrom:
        - configMapRef:
            name: runnergo-config
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092