# Generated by Django 4.2.30 on 2026-07-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_align_project_owner_and_member_constraints'),
        ('executions', '0004_align_test_run_case_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=80, unique=True, verbose_name='任务ID')),
                ('objective', models.CharField(max_length=500, verbose_name='测试目标')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='业务分析')),
                ('test_strategy', models.JSONField(blank=True, default=dict, verbose_name='测试策略')),
                ('created_assets', models.JSONField(blank=True, default=dict, verbose_name='创建的资产')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_tasks', to='projects.project', verbose_name='关联项目')),
                ('test_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_tasks', to='executions.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': 'AI测试Copilot任务',
                'verbose_name_plural': 'AI测试Copilot任务',
                'db_table': 'copilot_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
