# Generated by Django 4.2.30 on 2026-07-24 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_runtime_data_orchestration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(db_index=True, max_length=50, verbose_name='资产类型')),
                ('name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('status', models.CharField(choices=[('AVAILABLE', '可用'), ('LOCKED', '已锁定'), ('USED', '已使用'), ('EXPIRED', '已过期')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='资产状态')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='资产数据')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('lock_ttl_seconds', models.PositiveIntegerField(default=3600, verbose_name='锁定TTL秒数')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_assets', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_test_data_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试数据资产',
                'verbose_name_plural': '测试数据资产',
                'db_table': 'test_data_assets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDataAssetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('ui_automation', 'UI自动化'), ('app_automation', 'APP自动化'), ('api_automation', '接口自动化')], db_index=True, max_length=30, verbose_name='目标类型')),
                ('target_case_id', models.PositiveIntegerField(db_index=True, verbose_name='目标用例ID')),
                ('target_case_name', models.CharField(blank=True, default='', max_length=500, verbose_name='目标用例名称')),
                ('alias', models.CharField(max_length=100, verbose_name='上下文别名')),
                ('asset_type', models.CharField(db_index=True, max_length=50, verbose_name='资产类型')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='申请数量')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='资产过滤条件')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签过滤')),
                ('release_policy', models.CharField(choices=[('release', '执行后释放为可用'), ('mark_used', '执行后标记已使用'), ('expire', '执行后标记过期'), ('keep_locked', '执行后保持锁定')], default='release', max_length=20, verbose_name='释放策略')),
                ('inject_path', models.CharField(blank=True, default='', max_length=200, verbose_name='注入路径')),
                ('lock_ttl_seconds', models.PositiveIntegerField(default=3600, verbose_name='锁定TTL秒数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_asset_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试数据需求',
                'verbose_name_plural': '测试数据需求',
                'db_table': 'test_data_asset_requirements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDataAssetLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(db_index=True, max_length=30, verbose_name='目标类型')),
                ('target_case_id', models.PositiveIntegerField(db_index=True, verbose_name='目标用例ID')),
                ('target_case_name', models.CharField(blank=True, default='', max_length=500, verbose_name='目标用例名称')),
                ('execution_type', models.CharField(blank=True, default='', max_length=50, verbose_name='执行类型')),
                ('execution_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='执行ID')),
                ('alias', models.CharField(max_length=100, verbose_name='上下文别名')),
                ('status', models.CharField(choices=[('LOCKED', '已锁定'), ('RELEASED', '已释放'), ('USED', '已使用'), ('EXPIRED', '已过期'), ('CLEANED', '已清理')], db_index=True, default='LOCKED', max_length=20, verbose_name='租约状态')),
                ('release_policy', models.CharField(default='release', max_length=20, verbose_name='释放策略')),
                ('runtime_context_path', models.CharField(blank=True, default='', max_length=200, verbose_name='Runtime Context路径')),
                ('payload_snapshot', models.JSONField(blank=True, default=dict, verbose_name='申请数据快照')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='锁定时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('cleanup_result', models.JSONField(blank=True, default=dict, verbose_name='清理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.testdataasset')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_asset_leases', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='core.testdataassetrequirement')),
            ],
            options={
                'verbose_name': '测试数据租约',
                'verbose_name_plural': '测试数据租约',
                'db_table': 'test_data_asset_leases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testdataassetrequirement',
            index=models.Index(fields=['target_type', 'target_case_id', 'is_active'], name='test_data_a_target__28c68b_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataassetrequirement',
            index=models.Index(fields=['asset_type', 'is_active'], name='test_data_a_asset_t_d9c1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataassetlease',
            index=models.Index(fields=['execution_type', 'execution_id', 'status'], name='test_data_a_executi_173a47_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataassetlease',
            index=models.Index(fields=['target_type', 'target_case_id'], name='test_data_a_target__6ffc23_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataassetlease',
            index=models.Index(fields=['asset', 'status'], name='test_data_a_asset_i_ce56c4_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataasset',
            index=models.Index(fields=['asset_type', 'status'], name='test_data_a_asset_t_cd14df_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataasset',
            index=models.Index(fields=['locked_by', 'status'], name='test_data_a_locked__7f5432_idx'),
        ),
        migrations.AddIndex(
            model_name='testdataasset',
            index=models.Index(fields=['created_by'], name='test_data_a_created_4a34d0_idx'),
        ),
    ]
