# Generated by Django 4.2.30 on 2026-08-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_test_data_decision_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTestDataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('asset_type', models.CharField(default='CUSTOM', max_length=50, verbose_name='资产类型')),
                ('status', models.CharField(choices=[('PENDING', '排队中'), ('RUNNING', '生成中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='任务状态')),
                ('field_definitions', models.JSONField(default=list, verbose_name='字段定义')),
                ('total_count', models.PositiveBigIntegerField(verbose_name='目标条数')),
                ('generated_count', models.PositiveBigIntegerField(default=0, verbose_name='已生成条数')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度百分比')),
                ('batch_size', models.PositiveIntegerField(default=5000, verbose_name='进度更新批次')),
                ('output_format', models.CharField(choices=[('csv', 'CSV'), ('jsonl', 'JSONL')], default='csv', max_length=10, verbose_name='输出格式')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='test-data-bulk/%Y/%m/%d/', verbose_name='生成文件')),
                ('output_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA256')),
                ('seed', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='随机种子')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Celery任务ID')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='请求取消')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_test_data_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '大批量测试数据任务',
                'verbose_name_plural': '大批量测试数据任务',
                'db_table': 'bulk_test_data_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulktestdatajob',
            index=models.Index(fields=['created_by', 'status'], name='bulk_test_d_created_8b133f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulktestdatajob',
            index=models.Index(fields=['status', 'created_at'], name='bulk_test_d_status_e8abed_idx'),
        ),
    ]
