# Generated by Django 5.0 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_bulktestdatajob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktestdatajob',
            name='include_create_table',
            field=models.BooleanField(default=True, verbose_name='包含建表语句'),
        ),
        migrations.AddField(
            model_name='bulktestdatajob',
            name='sql_dialect',
            field=models.CharField(default='mysql', max_length=20, verbose_name='SQL方言'),
        ),
        migrations.AddField(
            model_name='bulktestdatajob',
            name='table_name',
            field=models.CharField(default='test_data', max_length=128, verbose_name='SQL目标表'),
        ),
        migrations.AlterField(
            model_name='bulktestdatajob',
            name='output_format',
            field=models.CharField(
                choices=[('csv', 'CSV'), ('jsonl', 'JSONL'), ('sql', 'SQL')],
                default='csv',
                max_length=10,
                verbose_name='输出格式',
            ),
        ),
    ]
