# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bulktestdatajob_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdataasset',
            name='bulk_job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_assets',
                to='core.bulktestdatajob',
                verbose_name='大批量生成任务',
            ),
        ),
        migrations.AddField(
            model_name='testdataasset',
            name='bulk_row_cursor',
            field=models.PositiveBigIntegerField(default=0, verbose_name='大批量数据游标'),
        ),
        migrations.AddField(
            model_name='bulktestdatajob',
            name='asset_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='数据资产配置'),
        ),
        migrations.AddField(
            model_name='bulktestdatajob',
            name='data_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bulk_source_jobs',
                to='core.testdataasset',
                verbose_name='生成的数据资产',
            ),
        ),
    ]
