# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bulk_data_asset_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdataassetrequirement',
            name='source_asset',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requirements',
                to='core.testdataasset',
                verbose_name='绑定的数据资产',
            ),
        ),
    ]
