# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testdataassetrequirement_source_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTestDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveBigIntegerField(verbose_name='行号')),
                ('payload', models.JSONField(default=dict, verbose_name='行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.bulktestdatajob')),
            ],
            options={
                'db_table': 'bulk_test_data_rows',
                'verbose_name': '大批量测试数据行',
                'verbose_name_plural': '大批量测试数据行',
            },
        ),
        migrations.AddConstraint(
            model_name='bulktestdatarow',
            constraint=models.UniqueConstraint(fields=('job', 'row_index'), name='uniq_bulk_test_data_job_row'),
        ),
        migrations.AddIndex(
            model_name='bulktestdatarow',
            index=models.Index(fields=['job', 'row_index'], name='bulk_test_d_job_id_8ae1f3_idx'),
        ),
    ]
